spring:
 application:
    name: currencyfactor
 datasource:
    url: jdbc:h2:mem:currencyfactor
    username: sa
    password: password
 management:
    endpoints:
      web:
        exposure:
         include: "*"
 eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      refresh:
        enable: false 
 server:
  port: 8080
 logging:
   level:
    org.springframework.web: DEBUG         