apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyfactor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyfactor
  template:
    metadata:
      labels:
        app: currencyfactor
    spec:
      containers:
      - name: currencyfactor
        image: microserviceapps/currencyfactor:1.0.0        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080